name: Build for Singularity

on:
  push:
    branches:
      - 3.13
    paths:
      - Singularity.def

  workflow_dispatch:
    inputs:
      Upload:
        description: 'Upload image to GoFile'
        required: false
        default: 'false'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 3.13
    
      - name: Set up Singularity
        uses: eWaterCycle/setup-singularity@v7
        with:
          singularity-version: 3.8.7
      
      - name: Get Rosetta
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          curl -O -u Academic_User:$PASSWORD https://www.rosettacommons.org/downloads/academic/3.13/rosetta_src_3.13_bundle.tgz
      
      - name: Limit threads
        run: |
          sed -i 's/100/6/g' Singularity.def

      - name: Build Rosetta
        run: |
          chmod +x build4singularity.sh
          ./build4singularity.sh

      - name: Test Rosetta
        run: |
          curl -O https://files.rcsb.org/view/3TDM.pdb
          singularity exec rosetta.sif score_jd2.mpi.linuxgccrelease -in:file:s 3TDM.pdb -ignore_unrecognized_res
      
      - name: Upload image
        if: github.event.inputs.Upload == 'true'
        run: |
          rm osetta_src_3.13_bundle.tgz
          mv rosetta.sif rosetta-3.13.sif && xz -9 rosetta-3.13.sif
          curl -fsSL git.io/file-transfer | bash
          ./transfer gof --no-progress rosetta-3.13.sif.xz 2>&1 | tee gofile.log
          echo "::warning file=gofile.io::$(cat gofile.log | grep https)"
          echo "name=$(cat gofile.log | grep https | cut -f3 -d" ")" >> $GITHUB_OUTPUT
